name: drtdi
description: A lightweight, powerful dependency injection container for Dart with support for multiple lifecycles, scoping, and decorators.
version: 1.0.0
homepage: https://github.com/c0dwiz/drtdi
repository: https://github.com/c0dwiz/drtdi

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.26.3
  benchmark_harness: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true